development:
  adapter: postgresql
  encoding: unicode
  database: tdd_bnb_development
  pool: 5
  username: tdd_bnb
  password:

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
